config/routes.rb
Rails.application.routes.draw do
  # Route for api -> v1 -> gps
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      #devise_for :users
      resources :gps, :only => [:show, :create, :update, :destroy]
    end
  end 
  # Route for controller gps
  resources :gps
  root to: 'gps#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gp.rb
class Gp < ApplicationRecord
end

app/controllers/api/v1/gps_controller.rb
class Api::V1::GpsController < ApplicationController
  respond_to :json

  def show
    respond_with Gp.find(params[:id])
  end

  def create
    gp = Gp.new(gp_params) 
      # if the gp is saved successfully than respond with json data and status code 201
    if gp.save 
      render json: gp, status: 201
    else
      render json: { errors: gp.errors}, status: 422
    end
  end

  def update
    gp = Gp.find(params[:id])

    if gp.update(gp_params)
      render json: gp, status: 200
    else
      render json: { errors: gp.errors }, status: 422
    end
  end

  def destroy
    gp = Gp.find(params[:id])
    gp.destroy
    head 204
  end

  private
  def gp_params
    params.require(:gp).permit(:latitude, :longitude, :sent_at, :vehicle_identifier) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/gps_controller.rb
class GpsController < ApplicationController

  def index
    @gps = Gp.all
  end

  def show
    @gp = Gp.find(params[:id]) 
  end
  # new gps
  def new
    @gp = Gp.new
  end
  # edit gps
  def edit
    @gp = Gp.find(params[:id])
  end
  # when new form call create
  def create
    @gp = Gp.new(gp_params)
    if @gp.save
      redirect_to @gp, notice: "Gps ha sido guardado correctamente."
    else
      render :new
    end
  end
  # when edit form call update
  def update
    @gp = Gp.find(params[:id])
    if @gp.update_attributes(gp_params)
      redirect_to @gp, notice: "Gps ha sido actualizado."
    else
      render :edit
    end
  end
  # delete gps
  def destroy
    @gp = Gp.find(params[:id])
    @gp.destroy
    redirect_to gps_url, notice: "Gps ha sido borrado."
  end
  
  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def gp_params
      params.require(:gp).permit(:latitude, :longitude, :sent_at, :vehicle_identifier)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gps_helper.rb
module GpsHelper
end

app/views/gps/_form.html.erb
<%= form_for(@gp) do |f| %>
  <% if @gp.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@gp.errors.count, "error") %> este gps esta prohibido para ser guardado:</h2>
      <ul>
      <% @gp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.number_field :latitude, :class => 'text_field', :step => 0.000001 %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.number_field :longitude, :class => 'text_field', :step => 0.000001 %>
  </div>
  <div class="field">
    <%= f.label :sent_at %><br />
    <%= f.text_field :sent_at %>
  </div>
  <div class="field">
    <%= f.label :vehicle_identifier %><br />
    <%= f.text_field :vehicle_identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gps/edit.html.erb
<h1>Editar Gps</h1>

<%= render 'form' %>

app/views/gps/index.html.erb
<h1>BeeTracker</h1>

<table id="gps">
  <tr>
    <th>latitude</th>
    <th>longitude</th>
    <th>sent_at</th>
    <th>vehicle_identifier</th>
  </tr>
  <% @gps.each do |gp| %>
    <tr>
      <td><%= gp.latitude %></td>
      <td><%= gp.longitude %></td>
      <td><%= gp.sent_at.strftime("%B %e, %Y") %></td>
      <td><%= link_to(gp.vehicle_identifier, gp) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Nuevo GPS", new_gp_path %></p>

app/views/gps/new.html.erb
<h1>Nuevo Gps</h1>

<%= render 'form' %>

app/views/gps/show.html.erb
<h1>lat:<%= @gp.latitude %>, lng:<%= @gp.longitude %></h1>

<p>
  <b>latitude:</b>
  <%= @gp.latitude %>
</p>

<p>
  <b>longitude:</b>
  <%= @gp.longitude %>
</p>

<p>
  <b>sent_at:</b>
  <%= @gp.sent_at.strftime("%B %e, %Y") %>
</p>

<p>
  <b>vehicle_identifier:</b>
  <%= @gp.vehicle_identifier %>
</p>

<div id="map"></div>

<%= link_to 'Editar', edit_gp_path(@gp) %> |
<%= link_to 'Destroy', @gps, method: :delete, confirm: "Are you sure?" %> |
<%= link_to 'Listar Gps', gps_path %>

<script>
  function initMap() {
    var uluru = {lat: <%= @gp.latitude %>, lng: <%= @gp.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 4,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAPI</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZYW8XYE6N5z2DxDbb8hvVVnfzpCLWo7o&callback=initMap"
    async defer></script>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>